- job:
    name: configure_jenkins
    description: 'Get updates from github and change the Jenkins'
    triggers:
      - github
      - pollscm:
          cron: "H/5 * * * *"
    scm:
      - git:
          url: "https://github.com/mbliznikova/many-faced.git"
          branches:
            - master
          basedir: configure_jenkins
    builders:
      - shell:
           jenkins-jobs --conf /<path-to-.ini-file>/jenkins_jobs.ini update $WORKSPACE/configure_jenkins/
